/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VexationIdRouteImport } from './routes/vexation/$id'
import { Route as SolutionIdRouteImport } from './routes/solution/$id'
import { Route as MyVexationsRouteImport } from './routes/my/vexations'
import { Route as MySavedRouteImport } from './routes/my/saved'
import { Route as MyClaimedRouteImport } from './routes/my/claimed'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VexationIdRoute = VexationIdRouteImport.update({
  id: '/vexation/$id',
  path: '/vexation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionIdRoute = SolutionIdRouteImport.update({
  id: '/solution/$id',
  path: '/solution/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyVexationsRoute = MyVexationsRouteImport.update({
  id: '/my/vexations',
  path: '/my/vexations',
  getParentRoute: () => rootRouteImport,
} as any)
const MySavedRoute = MySavedRouteImport.update({
  id: '/my/saved',
  path: '/my/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClaimedRoute = MyClaimedRouteImport.update({
  id: '/my/claimed',
  path: '/my/claimed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/portfolio': typeof PortfolioRoute
  '/signIn': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/my/claimed': typeof MyClaimedRoute
  '/my/saved': typeof MySavedRoute
  '/my/vexations': typeof MyVexationsRoute
  '/solution/$id': typeof SolutionIdRoute
  '/vexation/$id': typeof VexationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/portfolio': typeof PortfolioRoute
  '/signIn': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/my/claimed': typeof MyClaimedRoute
  '/my/saved': typeof MySavedRoute
  '/my/vexations': typeof MyVexationsRoute
  '/solution/$id': typeof SolutionIdRoute
  '/vexation/$id': typeof VexationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/portfolio': typeof PortfolioRoute
  '/signIn': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/my/claimed': typeof MyClaimedRoute
  '/my/saved': typeof MySavedRoute
  '/my/vexations': typeof MyVexationsRoute
  '/solution/$id': typeof SolutionIdRoute
  '/vexation/$id': typeof VexationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/complete-profile'
    | '/portfolio'
    | '/signIn'
    | '/submit'
    | '/my/claimed'
    | '/my/saved'
    | '/my/vexations'
    | '/solution/$id'
    | '/vexation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/complete-profile'
    | '/portfolio'
    | '/signIn'
    | '/submit'
    | '/my/claimed'
    | '/my/saved'
    | '/my/vexations'
    | '/solution/$id'
    | '/vexation/$id'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/complete-profile'
    | '/portfolio'
    | '/signIn'
    | '/submit'
    | '/my/claimed'
    | '/my/saved'
    | '/my/vexations'
    | '/solution/$id'
    | '/vexation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  PortfolioRoute: typeof PortfolioRoute
  SignInRoute: typeof SignInRoute
  SubmitRoute: typeof SubmitRoute
  MyClaimedRoute: typeof MyClaimedRoute
  MySavedRoute: typeof MySavedRoute
  MyVexationsRoute: typeof MyVexationsRoute
  SolutionIdRoute: typeof SolutionIdRoute
  VexationIdRoute: typeof VexationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vexation/$id': {
      id: '/vexation/$id'
      path: '/vexation/$id'
      fullPath: '/vexation/$id'
      preLoaderRoute: typeof VexationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solution/$id': {
      id: '/solution/$id'
      path: '/solution/$id'
      fullPath: '/solution/$id'
      preLoaderRoute: typeof SolutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/vexations': {
      id: '/my/vexations'
      path: '/my/vexations'
      fullPath: '/my/vexations'
      preLoaderRoute: typeof MyVexationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/saved': {
      id: '/my/saved'
      path: '/my/saved'
      fullPath: '/my/saved'
      preLoaderRoute: typeof MySavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/claimed': {
      id: '/my/claimed'
      path: '/my/claimed'
      fullPath: '/my/claimed'
      preLoaderRoute: typeof MyClaimedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  PortfolioRoute: PortfolioRoute,
  SignInRoute: SignInRoute,
  SubmitRoute: SubmitRoute,
  MyClaimedRoute: MyClaimedRoute,
  MySavedRoute: MySavedRoute,
  MyVexationsRoute: MyVexationsRoute,
  SolutionIdRoute: SolutionIdRoute,
  VexationIdRoute: VexationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
