/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as MyVexationsRouteImport } from './routes/my-vexations'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VexationIdRouteImport } from './routes/vexation/$id'
import { Route as MySavedRouteImport } from './routes/my/saved'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const MyVexationsRoute = MyVexationsRouteImport.update({
  id: '/my-vexations',
  path: '/my-vexations',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VexationIdRoute = VexationIdRouteImport.update({
  id: '/vexation/$id',
  path: '/vexation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MySavedRoute = MySavedRouteImport.update({
  id: '/my/saved',
  path: '/my/saved',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/my-vexations': typeof MyVexationsRoute
  '/signIn': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/my/saved': typeof MySavedRoute
  '/vexation/$id': typeof VexationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/my-vexations': typeof MyVexationsRoute
  '/signIn': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/my/saved': typeof MySavedRoute
  '/vexation/$id': typeof VexationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/my-vexations': typeof MyVexationsRoute
  '/signIn': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/my/saved': typeof MySavedRoute
  '/vexation/$id': typeof VexationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/my-vexations'
    | '/signIn'
    | '/submit'
    | '/my/saved'
    | '/vexation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/my-vexations'
    | '/signIn'
    | '/submit'
    | '/my/saved'
    | '/vexation/$id'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/my-vexations'
    | '/signIn'
    | '/submit'
    | '/my/saved'
    | '/vexation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  MyVexationsRoute: typeof MyVexationsRoute
  SignInRoute: typeof SignInRoute
  SubmitRoute: typeof SubmitRoute
  MySavedRoute: typeof MySavedRoute
  VexationIdRoute: typeof VexationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-vexations': {
      id: '/my-vexations'
      path: '/my-vexations'
      fullPath: '/my-vexations'
      preLoaderRoute: typeof MyVexationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vexation/$id': {
      id: '/vexation/$id'
      path: '/vexation/$id'
      fullPath: '/vexation/$id'
      preLoaderRoute: typeof VexationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/saved': {
      id: '/my/saved'
      path: '/my/saved'
      fullPath: '/my/saved'
      preLoaderRoute: typeof MySavedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  MyVexationsRoute: MyVexationsRoute,
  SignInRoute: SignInRoute,
  SubmitRoute: SubmitRoute,
  MySavedRoute: MySavedRoute,
  VexationIdRoute: VexationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
